name: Keep a Changelog

on:
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - run: bash -c "! git diff --exit-code origin/master... CHANGELOG.md"
