name: GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  pages:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: "1.56.0"
        profile: minimal
        default: true
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: doc
        args: --no-deps --all-features
    - name: Deploy GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/doc
        force_orphan: true
